### ISSUE TITLE
Drawr sans other data

### ISSUE THREAD

**Issue by nstrayer** [nstrayer/shinysense#11]
Just input raw data using shiny drawr. No plot to show up. This would allow things like draw a distribution or curve etc for exportation later.

**Comment by andrewpbray** [comment]
I amazed at how quickly you sketched this up. Hopefully soon I'll plug this into that Bayes' example to give a nice use case.

One thing: when I first tried out that demo script, I got:

```Warning: Error in tag: object 'raw_draw' not found```

I was able to mollify it by turning `code(raw_data)` into `code("raw_data")`. I'm not familiar enough with those shiny builder functions to know if this was an idiosyncratic fix for my configuration or something more general. If the latter, I'd be glad to submit a PR (or it's so simple I suppose you may just want to fix it).

Btw: this whole package is terrific!
