### ISSUE TITLE
Remove the on_done_drawing argument

### ISSUE THREAD

**Issue by muschellij2** [nstrayer/shinysense#13]
I can't seem to figure out how if I can currently use `shinydrawr` to:
1) Plot a portion of the data (but an x-axis that extends)
2) Have a user fill in the data for that.
3) Not have the "true" data revealed.

So either, can you pass in an `x_max` argument that overrides `x_max = scales.x.domain()[1]` (I'm not sure how good that'd be) where there is no "true" data passed in.  For example, a `data.frame` that ends with `x` = 5 but the x-axis extends to 10 and you want to fill it in.  Dislike this because you don't know the grid you want to fill in.

You can also have an additional flag for this block of code
```js
if (d3.mean(usersData, function (d) {
        return d.defined;
      }) === 1 && !this.raw_draw) {
        clipRect.transition().duration(1000).attr('width', scales.x(x_max));
      }
```
other than `raw_draw`.  I may not know how to use `raw_draw`, but it seems that I'd need another flag for this behavior because setting `raw_draw = TRUE` indicates nothing should be plotted initially.

**Comment by nstrayer** [comment]
This was fixed in https://github.com/nstrayer/shinysense/pull/15. To do this you now simply set the values for the x-areas you don't want revealed to be `NA` and the plot will not display them.  

e.g.
```
timeDataNoReveal <- timeData %>% 
  mutate(
    value = ifelse(date > endDate, NA, value)
  )
  
allModule(
  shinydrawr,
  "no_reveal",
  data = timeDataNoReveal,
  draw_start = endDate,
  x_key = "date",
  y_key = "value",
  y_min = 2
)
```
