### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ehbick01** [nstrayer/shinysense#17]
When running the most updated version, nothing is being output. Even running the example you use results in a blank screen:

![image](https://user-images.githubusercontent.com/4389349/29178731-6efcff36-7dc0-11e7-8987-9617badd8d48.png)

**Comment by nstrayer** [comment]
Fascinating and not great. 

Are you running on windows? The windows rstudio uses a old IE version underneath that doesnt support new JavaScript techniques (that i may have unwittingly used). 

If you are, try knitting something and viewing the result in chrome or edge or something.

**Comment by ehbick01** [comment]
That did the trick! Also, TIL that windows rstudio uses IE. And that is a bit depressing.

This package is awesome - thank you for building it out and supporting it!!
