### ISSUE TITLE
error on predict

### ISSUE THREAD

**Issue by nujcharee** [nstrayer/shinysense#24]
I got error message when running script on local machine using Chrome

Warning: Error in UseMethod: no applicable method for 'predict' applied to an object of class "character"
  [No stack trace available]

Any advice please? Thank you so much :)

**Comment by nstrayer** [comment]
Oops! Which demo are you running? [This one](https://github.com/nstrayer/shinysense/blob/master/demo/shinyviewr_demo.R) or [this one](https://github.com/nstrayer/viewr_imagenet_demo/blob/master/basic_demo.R)?

**Comment by nujcharee** [comment]
Ah I found out my error actually - I re-used one of the models I already had on my machine. Sorry about that.
