### ISSUE TITLE
trouble getting camera to work in shinysense

### ISSUE THREAD

**Issue by tbowling87** [nstrayer/shinysense#25]
Hi, really interesting package. I downloaded the shinysense code and was having issues getting the "uh-oh something went wrong" message despite allowing permission to use the camera and running on localhost through R studio. My first thoughts were that this was something up with my machine, maybe some video drivers that needed updating or something, but have tried accessing the demo link on my laptop (Latitude 7390 running Windows 10) (failed), iphone X (front and back failed) and Samsung Galaxy A5 (front worked back failed), I guess this might be a bigger issue. Let me know if there are any further details I can provide which will help

**Comment by nstrayer** [comment]
Hi @tbowling87, 

Well that's no good. You actually caught me at a good time as I am gearing up to do a big rehaul of the package to work through bugs. 

In order to help me find the bug could you paste the exact shiny app code you are using to get that error? Or the minimum app you can build to recreate the issue? This very well may be due to newer browsers implementing stricter camera permissions than when I initially made the function.

**Comment by tbowling87** [comment]
Hi, here is the code I was running on my laptop

`# Installs latest version of shinysense.
#devtools::install_github('nstrayer/shinysense')

# Installs latest version of keras. 
#devtools::install_github('rstudio/keras')

# Make sure you have the python versions of keras/tensorflow installed on your machine.
#keras::install_keras()
library(shiny)
library(shinysense)
library(tidyverse)

ui <- fluidPage(
  shinyviewrUI("myCamera", height = '200px'),
  imageOutput("snapshot")
)

server <- function(input, output) {
  #server side call of the drawr module
  myCamera <- callModule(
    shinyviewr, "myCamera", 
    outputHeight = 300,
    outputWidth = 400)
  
  # logic for what happens after a user has drawn their values. 
  observeEvent(myCamera(), {
    photo <- myCamera() 
    print(photo) #print to console for inspection
    output$snapshot <- renderPlot({
      plot(as.raster(photo)) # plot photo
    })
  })
}

# Run the application
shinyApp(ui = ui, server = server)`

It's just the basic intro bit from your blog post, and then the app I was running on the 2 mobiles was the test version linked in the readme.

Glad to hear it's a good time for you to look in to it, and let me know if there's any more info I can provide .

**Comment by nstrayer** [comment]
I have yet to dig into this but my first guess would be that the Keras api has changed or something. Once I get to this in the next bit I will follow up! Thanks for reporting it!

**Comment by dselivanov** [comment]
Here is the actual error- it looks like pure JS error:
<img width="1634" alt="Screen Shot 2019-09-09 at 12 38 41" src="https://user-images.githubusercontent.com/5123805/64516040-c8914300-d2fe-11e9-8899-63fa0e5bc42a.png">

**Comment by dselivanov** [comment]
And demo at [https://nstrayer.shinyapps.io/viewr_imagenet/](https://nstrayer.shinyapps.io/viewr_imagenet/) doesn't work.

**Comment by nstrayer** [comment]
@dselivanov , 

Thank you! What browser are you using there? I should be getting around to this in the next few days. Also are you running the demo in a secured environment? Aka `localhost` or `https`?
(It needs those to run but I also have neglected to put in a warning about that which I should do.)

**Comment by dselivanov** [comment]
I've just tried to open your demo (https). I've tried with several browsers
- Chrome, safari, chrome for Android.

пн, 9 сент. 2019 г., 21:49 Nick Strayer <notifications@github.com>:

**Comment by nstrayer** [comment]
Great. Thanks for the help. Ill ping here when it’s fixed!

**Comment by nstrayer** [comment]
Fixed this issue in https://github.com/nstrayer/shinysense/pull/32. Basically all browsers randomly shifted the syntax slightly for getting access to the camera. I have yet to push this update to the master branch (working on a full overhaul so committing to `version_2_dev` currently) so if you want to check it out before then you can run. 
```
devtools::install_github('nstrayer/shinysense', ref = 'version_2_dev')

shinysense::run_demo('shinyviewr')
```
If troubles persist I will reopen! 

Thanks for all your help!

**Comment by dselivanov** [comment]
Hi @nstrayer . Thanks for quick fix. However I see several issues -  undefined exports and errors in Rd files:

> * installing *source* package ‘shinysense’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
Warning: /private/var/folders/4d/8zbf173913v556657df4z40w0000gn/T/RtmpaiiFKY/R.INSTALL123539bd1a3f/shinysense/man/drawr.Rd:45: unknown macro '\item'
Warning: /private/var/folders/4d/8zbf173913v556657df4z40w0000gn/T/RtmpaiiFKY/R.INSTALL123539bd1a3f/shinysense/man/drawr.Rd:47: unknown macro '\item'
Warning: /private/var/folders/4d/8zbf173913v556657df4z40w0000gn/T/RtmpaiiFKY/R.INSTALL123539bd1a3f/shinysense/man/drawr.Rd:49: unexpected section header '\value'
Warning: /private/var/folders/4d/8zbf173913v556657df4z40w0000gn/T/RtmpaiiFKY/R.INSTALL123539bd1a3f/shinysense/man/drawr.Rd:52: unexpected section header '\description'
Warning: /private/var/folders/4d/8zbf173913v556657df4z40w0000gn/T/RtmpaiiFKY/R.INSTALL123539bd1a3f/shinysense/man/drawr.Rd:55: unexpected section header '\examples'
Warning: /private/var/folders/4d/8zbf173913v556657df4z40w0000gn/T/RtmpaiiFKY/R.INSTALL123539bd1a3f/shinysense/man/drawr.Rd:65: unexpected END_OF_INPUT '
'
Warning: /private/var/folders/4d/8zbf173913v556657df4z40w0000gn/T/RtmpaiiFKY/R.INSTALL123539bd1a3f/shinysense/man/shinydrawr.Rd:47: unknown macro '\item'
Warning: /private/var/folders/4d/8zbf173913v556657df4z40w0000gn/T/RtmpaiiFKY/R.INSTALL123539bd1a3f/shinysense/man/shinydrawr.Rd:49: unknown macro '\item'
Warning: /private/var/folders/4d/8zbf173913v556657df4z40w0000gn/T/RtmpaiiFKY/R.INSTALL123539bd1a3f/shinysense/man/shinydrawr.Rd:51: unexpected section header '\description'
Warning: /private/var/folders/4d/8zbf173913v556657df4z40w0000gn/T/RtmpaiiFKY/R.INSTALL123539bd1a3f/shinysense/man/shinydrawr.Rd:55: unexpected section header '\examples'
Warning: /private/var/folders/4d/8zbf173913v556657df4z40w0000gn/T/RtmpaiiFKY/R.INSTALL123539bd1a3f/shinysense/man/shinydrawr.Rd:67: unexpected END_OF_INPUT '
'
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘shinysense’ in namespaceExport(ns, exports):
 undefined exports: shinyearr, shinyearrUI
Error: loading failed
Execution halted
ERROR: loading failed
> * removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/shinysense’

**Comment by nstrayer** [comment]
Ah good catch! That was a result of me not knowing how to use roxygen and having a stray percent sign sitting in the docs. Fixed now in https://github.com/nstrayer/shinysense/pull/39

**Comment by dselivanov** [comment]
```
shinysense::run_demo('shinyviewr')
```
> Loading required package: shiny
> Error in library(tidyverse) : there is no package called ‘tidyverse’

need to add `tidyverse` it at least to suggests ;-)

Also I have a question - is it really necessary to have a dependency on all the "tidy" tools (which is pretty heavy)?

**Comment by dselivanov** [comment]
Also same thing about with `r2d3`:
> Error in loadNamespace(name) : there is no package called ‘r2d3’

Apart from that works perfectly. Thanks for great package!
