### ISSUE TITLE
library/3.4/shinysense/help/shinysense.rdb' is corrupt

### ISSUE THREAD

**Issue by ekoski1** [nstrayer/shinysense#43]
I try to install shinysense using 
`devtools::install_github('nstrayer/shinysense', force = TRUE)`

Then 
* DONE (shinysense)
> library(shinysense)
Error in fetch(key) :   lazy-load database '/home/eric/R/x86_64-pc-linux-gnu-library/3.4/shinysense/help/shinysense.rdb' is corrupt

I'm using 
RStudio Version 1.2.1335

platform       x86_64-pc-linux-gnu         
major          3                           
minor          4.4                         
year           2018                        
month          03                          
day            15                          
svn rev        74408                       
language       R                           
version.string R version 3.4.4 (2018-03-15)
nickname       Someone to Lean On   

I don't get as far as being able to run_demo(). 

Hope this gives you enough information. Thanks for your attention to this!

Eric 
ekoski1@gmail.com

**Comment by nstrayer** [comment]
Hi! 
This is my bad. I merged a PR into master and then never rebuilt the docs etc. I just updated with https://github.com/nstrayer/shinysense/commit/16758d5ef8dd53aa0b189260a0b3e4c9467430a8 and tested on my machine and it installed properly. Let me know if you're still having issues. Thanks for filing the issue!
