### ISSUE TITLE
how to save camera picture into jpg

### ISSUE THREAD

**Issue by TonyFly3000** [nstrayer/shinysense#44]
May I ask how to save camera picture into jpg ? 

 observeEvent(camera_snapshot(), {
    photo <- camera_snapshot() 
    writeImage(photo, 'photo.jpg', quality = 85)
  })

error :

Warning: Error in <Anonymous>: unable to find an inherited method for function ‘normalize’ for signature ‘"raster"’
  [No stack trace available]

**Comment by TonyFly3000** [comment]
solved.using


png(filename="cam.png")
plot(myCamera(), main = 'My Photo!')
dev.off()

**Comment by nstrayer** [comment]
Hi @TonyFly3000 , 

Sorry for the slow response and thanks so much for posting your solution so others may use it in the future!

Best,
Nick

**Comment by moldach** [comment]
Thanks for getting me started @TonyFly3000 

The following logic worked good for saving a file as well as keeping the `dev`/plot window open:

```
    # logic for what happens after a user has drawn their values. 
    observeEvent(myCamera(), {
      photo <- myCamera() 
      png(filename='cam.png')
      plot(as.raster(photo)) # plot photo
      dev.off()
      output$snapshot <- renderPlot({
        plot(as.raster(photo))
      })
    })
```
