### ISSUE TITLE
Towards CRAN?

### ISSUE THREAD

**Issue by jonthegeek** [nstrayer/shinysense#47]
Do you have any plans to push toward getting this onto CRAN? It sounds interesting, but our general policy at work is to stick with CRAN-published packages.

**Comment by nstrayer** [comment]
I made an effort to get it on cran a while ago but they rejected it because none of the example code could be run non-interactively. 

I haven't had the time since to figure out someway around that restriction.

**Comment by jonthegeek** [comment]
That makes sense. Maybe wrapping in `if (interactive())` would satisfy? I definitely need to figure out what it would take one of these days. Maybe use `shiny` examples as a guide?
